server:
  error:
    include-binding-errors: always
spring:
  h2:
    console:
      path: '/console'
      enabled: true
  datasource:
    url: jdbc:h2:file:./todo-db
  jpa:
    hibernate:
      ddl-auto: validate


